In [5]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [5]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [6]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [7]:
#matrix is sub part of array class

In [8]:
l1 = [1,2,3,4,5]

In [9]:
a = np.array(l1)

In [21]:
c = a#slow copy

In [11]:
c

array([1, 2, 3, 4, 5])

In [12]:
c[0]=101

In [13]:
c

array([101,   2,   3,   4,   5])

In [14]:
a

array([101,   2,   3,   4,   5])

In [20]:
d = a.copy()#deep copy

In [16]:
d

array([101,   2,   3,   4,   5])

In [17]:
d[1] = 99

In [18]:
d

array([101,  99,   3,   4,   5])

In [19]:
a

array([101,   2,   3,   4,   5])

In [22]:
np.fromfunction(lambda i,j:i==j,(5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [23]:
np.fromfunction(lambda i,j:i*j,(5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [24]:
iterable = (i*i for i in range(5))

In [26]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [27]:
np.fromstring('1 2 3 4 5 6',sep = ' ')

array([1., 2., 3., 4., 5., 6.])

In [28]:
np.fromstring('1,2,3,4,5',sep = ',')

array([1., 2., 3., 4., 5.])

In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr

array([1, 2, 3, 4, 5])

In [31]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [32]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
arr.ndim

1

In [34]:
arr1.ndim

2

In [35]:
arr.size

5

In [36]:
arr1.size

10

In [37]:
arr.shape

(5,)

In [38]:
arr1.shape

(2, 5)

In [41]:
arr.dtype

dtype('int64')

In [42]:
arr1.dtype

dtype('int64')

In [43]:
range(5)

range(0, 5)

In [44]:
list(range(5))

[0, 1, 2, 3, 4]

In [45]:
list(range(0.5,5))

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
np.arange(0.5,3,0.2)

array([0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9])

In [50]:
np.linspace(1,10,25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [7]:
np.logspace(1,10,25,base = 2)

array([   2.        ,    2.59367911,    3.36358566,    4.36203093,
          5.65685425,    7.33603235,    9.51365692,   12.3376866 ,
         16.        ,   20.74943287,   26.90868529,   34.89624745,
         45.254834  ,   58.68825877,   76.10925536,   98.70149283,
        128.        ,  165.995463  ,  215.2694823 ,  279.16997956,
        362.03867197,  469.50607012,  608.87404288,  789.61194261,
       1024.        ])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
np.zeros((5,4,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,5))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [16]:
np.ones((3,5))*6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.empty((3,6))

array([[4.64323706e-310, 0.00000000e+000, 6.90707695e-310,
        6.90707587e-310, 6.90707692e-310, 6.90707587e-310],
       [6.90707644e-310, 6.90707693e-310, 6.90707692e-310,
        6.90707699e-310, 6.90707702e-310, 6.90707702e-310],
       [6.90707695e-310, 6.90707690e-310, 6.90707702e-310,
        6.90707587e-310, 6.90707702e-310, 6.90707703e-310]])

In [21]:
import pandas as pd

In [23]:
np.random.randn(3,4)

array([[ 0.36622375, -0.52734854,  0.18936613, -0.02085647],
       [ 1.03172832, -0.20382563, -0.24169636,  0.53459232],
       [-0.08782359,  0.89836994, -1.13068472,  0.61858892]])

In [29]:
arr = np.random.rand(3,4)

In [25]:
np.random.randint(1,100,20)

array([34, 83, 65, 87, 62,  4, 23, 87, 82, 71,  5,  4, 28, 12, 26, 10, 83,
       33, 49, 23])

In [26]:
df = np.random.randint(1,100,500)

In [27]:
df1 = pd.DataFrame(df)

In [28]:
df1

0
0    52
1    71
2    41
3    79
4    34
..   ..
495  67
496   1
497  45
498  38
499  20

[500 rows x 1 columns]

In [30]:
arr

array([[0.62903953, 0.32398425, 0.48420711, 0.55952897],
       [0.67528915, 0.36160681, 0.05033819, 0.50350984],
       [0.31866769, 0.5790053 , 0.41135432, 0.18543495]])

In [33]:
arr = arr.reshape(6,2)

In [37]:
arr[1][1]

0.559528973271584

In [35]:
arr

array([[0.62903953, 0.32398425],
       [0.48420711, 0.55952897],
       [0.67528915, 0.36160681],
       [0.05033819, 0.50350984],
       [0.31866769, 0.5790053 ],
       [0.41135432, 0.18543495]])

In [41]:
arr[2:5,1]

array([0.36160681, 0.50350984, 0.5790053 ])

In [42]:
arr

array([[0.62903953, 0.32398425],
       [0.48420711, 0.55952897],
       [0.67528915, 0.36160681],
       [0.05033819, 0.50350984],
       [0.31866769, 0.5790053 ],
       [0.41135432, 0.18543495]])

In [46]:
arr[arr>0.5]

array([0.62903953, 0.55952897, 0.67528915, 0.50350984, 0.5790053 ])

In [47]:
arr = np.random.randint(1,100,20)

In [48]:
arr

array([17, 47, 40, 31,  2, 39, 43, 62, 26, 60, 84, 55, 92, 41, 47, 70,  2,
       88, 75, 37])

In [51]:
arr = arr.reshape(5,4)

In [52]:
arr

array([[17, 47, 40, 31],
       [ 2, 39, 43, 62],
       [26, 60, 84, 55],
       [92, 41, 47, 70],
       [ 2, 88, 75, 37]])

In [55]:
arr[2:4,1:3]

array([[60, 84],
       [41, 47]])

In [57]:
arr[0][0] = 10000

In [58]:
arr

array([[10000,    47,    40,    31],
       [    2,    39,    43,    62],
       [   26,    60,    84,    55],
       [   92,    41,    47,    70],
       [    2,    88,    75,    37]])

In [3]:
import numpy as np
arr1 = np.random.randint(1,100,(3,3))

In [4]:
arr2 = np.random.randint(1,100,(3,3))

In [62]:
arr1

array([[66,  7, 37],
       [79, 41, 52],
       [36, 11, 20]])

In [63]:
arr2

array([[69, 76, 86],
       [11, 81, 40],
       [40, 54, 89]])

In [64]:
arr1+arr2

array([[135,  83, 123],
       [ 90, 122,  92],
       [ 76,  65, 109]])

In [65]:
arr1*arr2

array([[4554,  532, 3182],
       [ 869, 3321, 2080],
       [1440,  594, 1780]])

In [66]:
arr1/arr2

array([[0.95652174, 0.09210526, 0.43023256],
       [7.18181818, 0.50617284, 1.3       ],
       [0.9       , 0.2037037 , 0.2247191 ]])

In [67]:
arr1/0

/tmp/ipykernel_5475/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [69]:
arr1@arr2

array([[ 6111,  7581,  9249],
       [ 7982, 12133, 13062],
       [ 3405,  4707,  5316]])

In [70]:
arr1+100

array([[166, 107, 137],
       [179, 141, 152],
       [136, 111, 120]])

In [71]:
arr1

array([[66,  7, 37],
       [79, 41, 52],
       [36, 11, 20]])

In [72]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
row = np.array([1,2,3])

In [79]:
row

array([1, 2, 3])

In [7]:
arr1+row

array([[63, 84, 86],
       [16, 89, 95],
       [50, 44, 24]])

In [8]:
arr1

array([[62, 82, 83],
       [15, 87, 92],
       [49, 42, 21]])

In [12]:
row = np.array([[1,2,3]])

In [10]:
row

array([1, 2, 3])

In [13]:
arr1+row.T

array([[63, 83, 84],
       [17, 89, 94],
       [52, 45, 24]])

In [14]:
arr1

array([[62, 82, 83],
       [15, 87, 92],
       [49, 42, 21]])

In [15]:
arr2

array([[14, 53, 73],
       [51, 99, 78],
       [79, 32, 28]])

In [16]:
arr2+row

array([[ 15,  55,  76],
       [ 52, 101,  81],
       [ 80,  34,  31]])

In [17]:
arr = np.random.randint(1,100,(3,4))

In [18]:
arr

array([[73, 94, 77, 91],
       [43, 68, 57, 25],
       [79, 29, 66, 20]])

In [19]:
np.log10(arr)

array([[1.86332286, 1.97312785, 1.88649073, 1.95904139],
       [1.63346846, 1.83250891, 1.75587486, 1.39794001],
       [1.89762709, 1.462398  , 1.81954394, 1.30103   ]])

In [20]:
np.square(arr)

array([[5329, 8836, 5929, 8281],
       [1849, 4624, 3249,  625],
       [6241,  841, 4356,  400]])

In [22]:
arr = np.random.randint(1,100,(3,4))

In [23]:
arr

array([[52, 39, 23, 52],
       [21, 84, 38, 70],
       [57, 49, 23,  7]])

In [24]:
arr.T

array([[52, 21, 57],
       [39, 84, 49],
       [23, 38, 23],
       [52, 70,  7]])

In [25]:
arr

array([[52, 39, 23, 52],
       [21, 84, 38, 70],
       [57, 49, 23,  7]])

In [28]:
arr.reshape(6,2)

array([[52, 39],
       [23, 52],
       [21, 84],
       [38, 70],
       [57, 49],
       [23,  7]])

In [29]:
arr

array([[52, 39, 23, 52],
       [21, 84, 38, 70],
       [57, 49, 23,  7]])

In [31]:
arr  = arr.flatten()

In [32]:
arr

array([52, 39, 23, 52, 21, 84, 38, 70, 57, 49, 23,  7])

In [33]:
np.expand_dims(arr,axis = 1)

array([[52],
       [39],
       [23],
       [52],
       [21],
       [84],
       [38],
       [70],
       [57],
       [49],
       [23],
       [ 7]])

In [35]:
np.expand_dims(arr,axis = 0)

array([[52, 39, 23, 52, 21, 84, 38, 70, 57, 49, 23,  7]])

In [36]:
arr1  = np.array([[1],[2],[3]])

In [37]:
arr1

array([[1],
       [2],
       [3]])

In [38]:
arr1.squeeze()

array([1, 2, 3])

In [39]:
np.repeat(arr,3)

array([52, 52, 52, 39, 39, 39, 23, 23, 23, 52, 52, 52, 21, 21, 21, 84, 84,
       84, 38, 38, 38, 70, 70, 70, 57, 57, 57, 49, 49, 49, 23, 23, 23,  7,
        7,  7])

In [40]:
np.roll(arr,3)

array([49, 23,  7, 52, 39, 23, 52, 21, 84, 38, 70, 57])

In [41]:
np.diag(arr)

array([[52,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 52,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 21,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 84,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 38,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 70,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 57,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 23,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7]])

In [42]:
arr1 = np.random.randint(1,100,(3,3))

In [43]:
arr2 = np.random.randint(1,100,(3,3))

In [44]:
arr1

array([[81, 82, 58],
       [55, 45, 71],
       [22, 69,  7]])

In [45]:
arr2

array([[32, 59, 38],
       [81, 14, 29],
       [57, 27, 93]])

In [46]:
arr1+arr2

array([[113, 141,  96],
       [136,  59, 100],
       [ 79,  96, 100]])

In [47]:
arr1*arr2

array([[2592, 4838, 2204],
       [4455,  630, 2059],
       [1254, 1863,  651]])

In [48]:
arr1/arr2

array([[2.53125   , 1.38983051, 1.52631579],
       [0.67901235, 3.21428571, 2.44827586],
       [0.38596491, 2.55555556, 0.07526882]])

In [49]:
arr1%arr2

array([[17, 23, 20],
       [55,  3, 13],
       [22, 15,  7]])

In [50]:
arr1/0

/tmp/ipykernel_6347/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [51]:
arr1&arr2

array([[ 0, 18, 34],
       [17, 12,  5],
       [16,  1,  5]])

In [52]:
arr1|arr2

array([[113, 123,  62],
       [119,  47,  95],
       [ 63,  95,  95]])

In [53]:
~arr1

array([[-82, -83, -59],
       [-56, -46, -72],
       [-23, -70,  -8]])

In [54]:
arr1>arr2

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True, False]])

In [55]:
arr1[arr1>arr2]

array([81, 82, 58, 45, 71, 69])

In [56]:
arr = np.array(['arjun','manjeet','kalu'])

In [57]:
np.char.upper(arr)

array(['ARJUN', 'MANJEET', 'KALU'], dtype='<U7')

In [59]:
np.char.split(arr[0])

array(list(['arjun']), dtype=object)

In [63]:
np.power(arr1,2)

array([[6561, 6724, 3364],
       [3025, 2025, 5041],
       [ 484, 4761,   49]])

In [65]:
np.mean(arr1)

54.44444444444444

In [66]:
np.median(arr1)

58.0

In [67]:
np.max(arr1)

82

In [68]:
np.min(arr1)

7

In [69]:
np.square(arr1)

array([[6561, 6724, 3364],
       [3025, 2025, 5041],
       [ 484, 4761,   49]])

In [70]:
#sort

In [71]:
arr = np.array([1,43,56,23,54,3,767,89,6,78,56,87,9])

In [73]:
arr

array([  1,  43,  56,  23,  54,   3, 767,  89,   6,  78,  56,  87,   9])

In [74]:
np.sort(arr)

array([  1,   3,   6,   9,  23,  43,  54,  56,  56,  78,  87,  89, 767])

In [ ]:
np.searchsorted(arr,2)